### ISSUE TITLE
[Suggestion] Proper Documentation Syntax

### ISSUE THREAD

**Issue by Nucs** [SciSharp/CodeMinion#4]
I wanted to copy documentation from `Numpy.NET` to use in `NumSharp` and noticed that the documentation there looks like the following:
```C#

/// <summary>
/// Return evenly spaced values within a given interval.
/// 
/// Values are generated within the half-open interval [start, stop)
/// (in other words, the interval including start but excluding stop).
/// For integer arguments the function is equivalent to the Python built-in
/// range function, but returns an ndarray rather than a list.
/// 
/// When using a non-integer step, such as 0.1, the results will often not
/// be consistent.  It is better to use numpy.linspace for these cases.
/// </summary>
/// <param name="start">
/// Start of interval.  The interval includes this value.  The default
/// start value is 0.
/// </param>
/// <param name="stop">
/// End of interval.  The interval does not include this value, except
/// in some cases where step is not an integer and floating point
/// round-off affects the length of out.
/// </param>
/// <param name="step">
/// Spacing between values.  For any output out, this is the distance
/// between two adjacent values, out[i+1] - out[i].  The default
/// step size is 1.  If step is specified as a position argument,
/// start must also be given.
/// </param>
/// <param name="dtype">
/// The type of the output array.  If dtype is not given, infer the data
/// type from the other input arguments.
/// </param>
/// <returns>
/// Array of evenly spaced values.
/// 
/// For floating point arguments, the length of the result is
/// ceil((stop - start)/step).  Because of floating point overflow,
/// this rule may result in the last element of out being greater
/// than stop.
/// </returns>
public static NDarray arange(short start, short stop, short step = 1, Dtype dtype = null)
    => NumPy.Instance.arange(start, stop, step:step, dtype:dtype);
```

When you view it in quick-view, it looks like this:
![image](https://user-images.githubusercontent.com/649919/60301945-3c948f80-993b-11e9-8a84-bb34ba1dc5db.png)

If you replace every end of sentence with `<br></br>`, it looks like this which is much more readable (this example is not even on the worst case): 
![image](https://user-images.githubusercontent.com/649919/60302367-6f8b5300-993c-11e9-9003-06fc9c64dc18.png)

Made a quick regex to help find end of sentences.
```Regex
(?:(?<=\w|\)|\])(?<!\d)|(?<=\s\d))\.(?=(?:\s|$))
```
Live: https://regex101.com/r/SmjBsp/1
Usage: `Regex.Replace(input, regex, ".<br></br>\n", RegexOptions.MultiLine)`

It is also common to add `\t` before start of each line just to make it much more comfy to the eye.

![image](https://user-images.githubusercontent.com/649919/60302891-b62d7d00-993d-11e9-9470-19cc10a71b01.png)

**Comment by Nucs** [comment]
I also want to mention that you guys perform not an easy task - this is already beyond great to even have docs.

**Comment by Oceania2018** [comment]
@Nucs I like the first one, more compat.

**Comment by henon** [comment]
@Nucs no problem to implement any changes. I only need to add it and give the Minion a spank with the rod to do it for us 😆

**Comment by Nucs** [comment]
Oh boi, now I know why it's called CodeMinion. 😂

**Comment by henon** [comment]
The Minion didn't even break a sweat. Check out the Numpy sources in CodeMinion which I regenerated with the new format.

**Comment by Nucs** [comment]
@henon pushed the changes.
